package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"io/fs"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

type structInfo struct {
	name   string
	fields []*ast.Field
}

func main() {
	var rootDir string
	flag.StringVar(&rootDir, "dir", ".", "root directory to scan for Go packages")
	flag.Parse()

	if len(flag.Args()) > 0 {
		rootDir = flag.Args()[0]
	}

	err := processDirectory(rootDir)
	if err != nil {
		log.Fatalf("Failed to generate reset functions: %v", err)
	}
}

func processDirectory(rootDir string) error {
	return filepath.WalkDir(rootDir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if d.IsDir() {
			name := d.Name()
			if (strings.HasPrefix(name, ".") && name != ".") || name == "vendor" || name == "node_modules" {
				return filepath.SkipDir
			}
			if err := generateResetForDir(path); err != nil {
				return fmt.Errorf("error processing dir %s: %w", path, err)
			}
		}
		return nil
	})
}

func generateResetForDir(dirPath string) error {
	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax,
		Dir:  dirPath,
		Env:  append(os.Environ(), "GO111MODULE=off"),
	}
	pkgs, err := packages.Load(cfg, ".")
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		if len(pkg.Syntax) == 0 {
			continue
		}

		var structs []structInfo

		files := make([]*ast.File, len(pkg.Syntax))
		copy(files, pkg.Syntax)
		sort.Slice(files, func(i, j int) bool {
			fnI := pkg.Fset.Position(files[i].Pos()).Filename
			fnJ := pkg.Fset.Position(files[j].Pos()).Filename
			return fnI < fnJ
		})

		for _, file := range files {
			filename := filepath.Base(pkg.Fset.Position(file.Pos()).Filename)
			if strings.HasSuffix(filename, "_test.go") || filename == "reset.gen.go" {
				continue
			}

			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					structType, ok := typeSpec.Type.(*ast.StructType)
					if !ok {
						continue
					}

					if hasGenerateResetComment(genDecl.Doc, typeSpec.Doc) {
						structs = append(structs, structInfo{
							name:   typeSpec.Name.Name,
							fields: structType.Fields.List,
						})
					}
				}
			}
		}

		genPath := filepath.Join(dirPath, "reset.gen.go")
		if len(structs) == 0 {
			if _, err := os.Stat(genPath); err == nil {
				_ = os.Remove(genPath)
			}
			continue
		}

		sort.Slice(structs, func(i, j int) bool {
			return structs[i].name < structs[j].name
		})

		var buf bytes.Buffer
		buf.WriteString("// Code generated by reset generator; DO NOT EDIT.\n\n")
		buf.WriteString("package "); buf.WriteString(pkg.Name); buf.WriteString("\n\n")

		for _, st := range structs {
			rec := getReceiverName(st.name)
			fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", rec, st.name)
			fmt.Fprintf(&buf, "\tif %s == nil {\n\t\treturn\n\t}\n\n", rec)

			for _, field := range st.fields {
				var names []string
				if len(field.Names) == 0 {
					embName := getEmbeddedFieldName(field.Type)
					if embName != "" {
						names = append(names, embName)
					}
				} else {
					for _, nameIdent := range field.Names {
						names = append(names, nameIdent.Name)
					}
				}

				for _, fname := range names {
					genFieldReset(&buf, rec, fname, field.Type)
				}
			}

			buf.WriteString("}\n\n")
		}

		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			return fmt.Errorf("failed to format generated code for %s: %w", genPath, err)
		}

		if err := os.WriteFile(genPath, formatted, 0644); err != nil {
			return fmt.Errorf("failed to write generated file %s: %w", genPath, err)
		}
		fmt.Printf("Generated %s\n", genPath)
	}

	return nil
}

func hasGenerateResetComment(declDoc *ast.CommentGroup, specDoc *ast.CommentGroup) bool {
	return checkCommentGroup(declDoc) || checkCommentGroup(specDoc)
}

func checkCommentGroup(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(c.Text)
		if text == "// generate:reset" || text == "//generate:reset" {
			return true
		}
	}
	return false
}

func getReceiverName(structName string) string {
	if len(structName) == 0 {
		return "r"
	}
	var initials []rune
	for i, r := range structName {
		if i == 0 || (r >= 'A' && r <= 'Z') {
			initials = append(initials, r)
		}
	}
	rec := strings.ToLower(string(initials))
	if rec == "" || isKeyword(rec) {
		return strings.ToLower(structName[:1])
	}
	return rec
}

func isKeyword(s string) bool {
	keywords := map[string]bool{
		"break": true, "default": true, "func": true, "interface": true, "select": true,
		"case": true, "defer": true, "go": true, "map": true, "struct": true,
		"chan": true, "else": true, "goto": true, "package": true, "switch": true,
		"const": true, "fallthrough": true, "if": true, "range": true, "type": true,
		"continue": true, "for": true, "import": true, "return": true, "var": true,
	}
	return keywords[s]
}

func getEmbeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return getEmbeddedFieldName(t.X)
	}
	return ""
}

func getPrimitiveKind(expr ast.Expr) string {
	ident, ok := expr.(*ast.Ident)
	if !ok {
		return ""
	}
	switch ident.Name {
	case "string":
		return "string"
	case "bool":
		return "bool"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"byte", "rune", "float32", "float64", "complex64", "complex128":
		return "numeric"
	}
	return ""
}

func genFieldReset(buf *bytes.Buffer, rec, fname string, expr ast.Expr) {
	target := fmt.Sprintf("%s.%s", rec, fname)

	switch t := expr.(type) {
	case *ast.StarExpr:
		kind := getPrimitiveKind(t.X)
		switch kind {
		case "string":
			fmt.Fprintf(buf, "\tif %s != nil {\n\t\t*%s = \"\"\n\t}\n", target, target)
		case "bool":
			fmt.Fprintf(buf, "\tif %s != nil {\n\t\t*%s = false\n\t}\n", target, target)
		case "numeric":
			fmt.Fprintf(buf, "\tif %s != nil {\n\t\t*%s = 0\n\t}\n", target, target)
		default:
			if arr, ok := t.X.(*ast.ArrayType); ok && arr.Len == nil {
				fmt.Fprintf(buf, "\tif %s != nil {\n\t\t*%s = (*%s)[:0]\n\t}\n", target, target, target)
			} else if _, ok := t.X.(*ast.MapType); ok {
				fmt.Fprintf(buf, "\tif %s != nil {\n\t\tclear(*%s)\n\t}\n", target, target)
			} else {
				fmt.Fprintf(buf, "\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\t\tresetter.Reset()\n\t}\n", target, target)
			}
		}
	case *ast.ArrayType:
		if t.Len == nil {
			fmt.Fprintf(buf, "\t%s = %s[:0]\n", target, target)
		} else {
			fmt.Fprintf(buf, "\tclear(%s)\n", target)
		}
	case *ast.MapType:
		fmt.Fprintf(buf, "\tclear(%s)\n", target)
	case *ast.InterfaceType:
		fmt.Fprintf(buf, "\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\t\tresetter.Reset()\n\t}\n", target, target)
	default:
		kind := getPrimitiveKind(expr)
		switch kind {
		case "string":
			fmt.Fprintf(buf, "\t%s = \"\"\n", target)
		case "bool":
			fmt.Fprintf(buf, "\t%s = false\n", target)
		case "numeric":
			fmt.Fprintf(buf, "\t%s = 0\n", target)
		default:
			if ident, ok := expr.(*ast.Ident); ok && ident.Name == "any" {
				fmt.Fprintf(buf, "\tif resetter, ok := any(%s).(interface{ Reset() }); ok && %s != nil {\n\t\tresetter.Reset()\n\t}\n", target, target)
			} else {
				fmt.Fprintf(buf, "\tif resetter, ok := any(&%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n", target)
			}
		}
	}
}
